package com.itss.vn.shops.entity;
// Generated Aug 2, 2017 4:33:40 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActionTransLog generated by hbm2java
 */
@Entity
@Table(name = "action_trans_log", catalog = "shops")
public class ActionTransLog implements java.io.Serializable {

	private Integer actionTransLogId;
	private String actionCode;
	private String actionName;
	private String staffCode;
	private Date createdTime;

	public ActionTransLog() {
	}

	public ActionTransLog(String actionCode, String actionName, String staffCode) {
		this.actionCode = actionCode;
		this.actionName = actionName;
		this.staffCode = staffCode;
	}

	public ActionTransLog(String actionCode, String actionName, String staffCode, Date createdTime) {
		this.actionCode = actionCode;
		this.actionName = actionName;
		this.staffCode = staffCode;
		this.createdTime = createdTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "action_trans_log_id", unique = true, nullable = false)
	public Integer getActionTransLogId() {
		return this.actionTransLogId;
	}

	public void setActionTransLogId(Integer actionTransLogId) {
		this.actionTransLogId = actionTransLogId;
	}

	@Column(name = "action_code", nullable = false, length = 20)
	public String getActionCode() {
		return this.actionCode;
	}

	public void setActionCode(String actionCode) {
		this.actionCode = actionCode;
	}

	@Column(name = "action_name", nullable = false, length = 50)
	public String getActionName() {
		return this.actionName;
	}

	public void setActionName(String actionName) {
		this.actionName = actionName;
	}

	@Column(name = "staff_code", nullable = false, length = 20)
	public String getStaffCode() {
		return this.staffCode;
	}

	public void setStaffCode(String staffCode) {
		this.staffCode = staffCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

}
