package com.itss.vn.shops.entity;
// Generated Aug 2, 2017 4:33:40 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActionTransLogDetail generated by hbm2java
 */
@Entity
@Table(name = "action_trans_log_detail", catalog = "shops")
public class ActionTransLogDetail implements java.io.Serializable {

	private Integer actionTransLogDetailId;
	private int actionTransLogId;
	private String tableName;
	private String columnName;
	private int columnId;
	private String oldValue;
	private String newValue;
	private String actionDetailDesc;
	private String staffCode;
	private Date createdTime;

	public ActionTransLogDetail() {
	}

	public ActionTransLogDetail(int actionTransLogId, String tableName, String columnName, int columnId,
			String oldValue, String newValue, String actionDetailDesc, String staffCode) {
		this.actionTransLogId = actionTransLogId;
		this.tableName = tableName;
		this.columnName = columnName;
		this.columnId = columnId;
		this.oldValue = oldValue;
		this.newValue = newValue;
		this.actionDetailDesc = actionDetailDesc;
		this.staffCode = staffCode;
	}

	public ActionTransLogDetail(int actionTransLogId, String tableName, String columnName, int columnId,
			String oldValue, String newValue, String actionDetailDesc, String staffCode, Date createdTime) {
		this.actionTransLogId = actionTransLogId;
		this.tableName = tableName;
		this.columnName = columnName;
		this.columnId = columnId;
		this.oldValue = oldValue;
		this.newValue = newValue;
		this.actionDetailDesc = actionDetailDesc;
		this.staffCode = staffCode;
		this.createdTime = createdTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "action_trans_log_detail_id", unique = true, nullable = false)
	public Integer getActionTransLogDetailId() {
		return this.actionTransLogDetailId;
	}

	public void setActionTransLogDetailId(Integer actionTransLogDetailId) {
		this.actionTransLogDetailId = actionTransLogDetailId;
	}

	@Column(name = "action_trans_log_id", nullable = false)
	public int getActionTransLogId() {
		return this.actionTransLogId;
	}

	public void setActionTransLogId(int actionTransLogId) {
		this.actionTransLogId = actionTransLogId;
	}

	@Column(name = "table_name", nullable = false, length = 50)
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	@Column(name = "column_name", nullable = false, length = 50)
	public String getColumnName() {
		return this.columnName;
	}

	public void setColumnName(String columnName) {
		this.columnName = columnName;
	}

	@Column(name = "column_id", nullable = false)
	public int getColumnId() {
		return this.columnId;
	}

	public void setColumnId(int columnId) {
		this.columnId = columnId;
	}

	@Column(name = "old_value", nullable = false, length = 50)
	public String getOldValue() {
		return this.oldValue;
	}

	public void setOldValue(String oldValue) {
		this.oldValue = oldValue;
	}

	@Column(name = "new_value", nullable = false, length = 50)
	public String getNewValue() {
		return this.newValue;
	}

	public void setNewValue(String newValue) {
		this.newValue = newValue;
	}

	@Column(name = "action_detail_desc", nullable = false)
	public String getActionDetailDesc() {
		return this.actionDetailDesc;
	}

	public void setActionDetailDesc(String actionDetailDesc) {
		this.actionDetailDesc = actionDetailDesc;
	}

	@Column(name = "staff_code", nullable = false, length = 20)
	public String getStaffCode() {
		return this.staffCode;
	}

	public void setStaffCode(String staffCode) {
		this.staffCode = staffCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

}
