package com.itss.vn.shops.entity;
// Generated Aug 31, 2017 9:41:01 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * AttributeGroups generated by hbm2java
 */
@Entity
@Table(name = "attribute_groups", catalog = "shops", uniqueConstraints = @UniqueConstraint(columnNames = "attribute_group_code"))
public class AttributeGroups implements java.io.Serializable {

    private Integer attributeGroupId;
    private String attributeGroupCode;
    private String attributeGroupName;
    private String attributeGroupDesc;
    private String staffCodeCreate;
    private String staffCodeUpdate;
    private Integer status;
    private Date updatedTime;
    private Date createdTime;

    public AttributeGroups() {
    }

    public AttributeGroups(int attributeGroupId, String attributeGroupCode, String attributeGroupName,
                           String staffCodeCreate, String staffCodeUpdate) {
        this.attributeGroupId = attributeGroupId;
        this.attributeGroupCode = attributeGroupCode;
        this.attributeGroupName = attributeGroupName;
        this.staffCodeCreate = staffCodeCreate;
        this.staffCodeUpdate = staffCodeUpdate;
    }

    public AttributeGroups(int attributeGroupId, String attributeGroupCode, String attributeGroupName,
                           String attributeGroupDesc, String staffCodeCreate, String staffCodeUpdate, Integer status, Date updatedTime,
                           Date createdTime) {
        this.attributeGroupId = attributeGroupId;
        this.attributeGroupCode = attributeGroupCode;
        this.attributeGroupName = attributeGroupName;
        this.attributeGroupDesc = attributeGroupDesc;
        this.staffCodeCreate = staffCodeCreate;
        this.staffCodeUpdate = staffCodeUpdate;
        this.status = status;
        this.updatedTime = updatedTime;
        this.createdTime = createdTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "attribute_group_id", unique = true, nullable = false)
    public Integer getAttributeGroupId() {
        return this.attributeGroupId;
    }

    public void setAttributeGroupId(Integer attributeGroupId) {
        this.attributeGroupId = attributeGroupId;
    }

    @Column(name = "attribute_group_code", unique = true, nullable = false, length = 20)
    public String getAttributeGroupCode() {
        return this.attributeGroupCode;
    }

    public void setAttributeGroupCode(String attributeGroupCode) {
        this.attributeGroupCode = attributeGroupCode;
    }

    @Column(name = "attribute_group_name", nullable = false, length = 50)
    public String getAttributeGroupName() {
        return this.attributeGroupName;
    }

    public void setAttributeGroupName(String attributeGroupName) {
        this.attributeGroupName = attributeGroupName;
    }

    @Column(name = "attribute_group_desc")
    public String getAttributeGroupDesc() {
        return this.attributeGroupDesc;
    }

    public void setAttributeGroupDesc(String attributeGroupDesc) {
        this.attributeGroupDesc = attributeGroupDesc;
    }

    @Column(name = "staff_code_create", nullable = false, length = 20)
    public String getStaffCodeCreate() {
        return this.staffCodeCreate;
    }

    public void setStaffCodeCreate(String staffCodeCreate) {
        this.staffCodeCreate = staffCodeCreate;
    }

    @Column(name = "staff_code_update", nullable = false, length = 20)
    public String getStaffCodeUpdate() {
        return this.staffCodeUpdate;
    }

    public void setStaffCodeUpdate(String staffCodeUpdate) {
        this.staffCodeUpdate = staffCodeUpdate;
    }

    @Column(name = "status")
    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_time", length = 19)
    public Date getUpdatedTime() {
        return this.updatedTime;
    }

    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_time", length = 19)
    public Date getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

}
