package com.itss.vn.shops.entity;
// Generated Aug 31, 2017 9:41:01 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Attribute generated by hbm2java
 */
@Entity
@Table(name = "attribute", catalog = "shops", uniqueConstraints = @UniqueConstraint(columnNames = "attribute_code"))
public class Attribute implements java.io.Serializable {

    private Integer attributeId;
    private int attributeGroupId;
    private String attributeCode;
    private String attributeName;
    private String attributeDesc;
    private String staffCodeCreate;
    private String staffCodeUpdate;
    private Integer status;
    private Date updatedTime;
    private Date createdTime;

    public Attribute() {
    }

    public Attribute(int attributeId, int attributeGroupId, String attributeCode, String attributeName,
                     String staffCodeCreate, String staffCodeUpdate) {
        this.attributeId = attributeId;
        this.attributeGroupId = attributeGroupId;
        this.attributeCode = attributeCode;
        this.attributeName = attributeName;
        this.staffCodeCreate = staffCodeCreate;
        this.staffCodeUpdate = staffCodeUpdate;
    }

    public Attribute(int attributeId, int attributeGroupId, String attributeCode, String attributeName,
                     String attributeDesc, String staffCodeCreate, String staffCodeUpdate, Integer status, Date updatedTime,
                     Date createdTime) {
        this.attributeId = attributeId;
        this.attributeGroupId = attributeGroupId;
        this.attributeCode = attributeCode;
        this.attributeName = attributeName;
        this.attributeDesc = attributeDesc;
        this.staffCodeCreate = staffCodeCreate;
        this.staffCodeUpdate = staffCodeUpdate;
        this.status = status;
        this.updatedTime = updatedTime;
        this.createdTime = createdTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "attribute_id", unique = true, nullable = false)
    public Integer getAttributeId() {
        return this.attributeId;
    }

    public void setAttributeId(Integer attributeId) {
        this.attributeId = attributeId;
    }

    @Column(name = "attribute_group_id", nullable = false)
    public int getAttributeGroupId() {
        return this.attributeGroupId;
    }

    public void setAttributeGroupId(int attributeGroupId) {
        this.attributeGroupId = attributeGroupId;
    }

    @Column(name = "attribute_code", unique = true, nullable = false, length = 20)
    public String getAttributeCode() {
        return this.attributeCode;
    }

    public void setAttributeCode(String attributeCode) {
        this.attributeCode = attributeCode;
    }

    @Column(name = "attribute_name", nullable = false, length = 50)
    public String getAttributeName() {
        return this.attributeName;
    }

    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName;
    }

    @Column(name = "attribute_desc")
    public String getAttributeDesc() {
        return this.attributeDesc;
    }

    public void setAttributeDesc(String attributeDesc) {
        this.attributeDesc = attributeDesc;
    }

    @Column(name = "staff_code_create", nullable = false, length = 20)
    public String getStaffCodeCreate() {
        return this.staffCodeCreate;
    }

    public void setStaffCodeCreate(String staffCodeCreate) {
        this.staffCodeCreate = staffCodeCreate;
    }

    @Column(name = "staff_code_update", nullable = false, length = 20)
    public String getStaffCodeUpdate() {
        return this.staffCodeUpdate;
    }

    public void setStaffCodeUpdate(String staffCodeUpdate) {
        this.staffCodeUpdate = staffCodeUpdate;
    }

    @Column(name = "status")
    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_time", length = 19)
    public Date getUpdatedTime() {
        return this.updatedTime;
    }

    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_time", length = 19)
    public Date getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

}
