package com.itss.vn.shops.entity;
// Generated Aug 31, 2017 9:41:01 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Finished generated by hbm2java
 */
@Entity
@Table(name = "finished", catalog = "shops", uniqueConstraints = @UniqueConstraint(columnNames = "finished_code"))
public class Finished implements java.io.Serializable {

    private Integer finishedId;
    private String finishedCode;
    private String finishedName;
    private int quantity;
    private int quantityRes;
    private float price;
    private String staffCodeCreate;
    private String staffCodeUpdate;
    private Integer status;
    private Date updatedTime;
    private Date createdTime;

    public Finished() {
    }

    public Finished(int finishedId, String finishedCode, String finishedName, int quantity, int quantityRes,
                    float price, String staffCodeCreate, String staffCodeUpdate) {
        this.finishedId = finishedId;
        this.finishedCode = finishedCode;
        this.finishedName = finishedName;
        this.quantity = quantity;
        this.quantityRes = quantityRes;
        this.price = price;
        this.staffCodeCreate = staffCodeCreate;
        this.staffCodeUpdate = staffCodeUpdate;
    }

    public Finished(int finishedId, String finishedCode, String finishedName, int quantity, int quantityRes,
                    float price, String staffCodeCreate, String staffCodeUpdate, Integer status, Date updatedTime,
                    Date createdTime) {
        this.finishedId = finishedId;
        this.finishedCode = finishedCode;
        this.finishedName = finishedName;
        this.quantity = quantity;
        this.quantityRes = quantityRes;
        this.price = price;
        this.staffCodeCreate = staffCodeCreate;
        this.staffCodeUpdate = staffCodeUpdate;
        this.status = status;
        this.updatedTime = updatedTime;
        this.createdTime = createdTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "finished_id", unique = true, nullable = false)
    public Integer getFinishedId() {
        return this.finishedId;
    }

    public void setFinishedId(Integer finishedId) {
        this.finishedId = finishedId;
    }

    @Column(name = "finished_code", unique = true, nullable = false, length = 20)
    public String getFinishedCode() {
        return this.finishedCode;
    }

    public void setFinishedCode(String finishedCode) {
        this.finishedCode = finishedCode;
    }

    @Column(name = "finished_name", nullable = false, length = 50)
    public String getFinishedName() {
        return this.finishedName;
    }

    public void setFinishedName(String finishedName) {
        this.finishedName = finishedName;
    }

    @Column(name = "quantity", nullable = false)
    public int getQuantity() {
        return this.quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    @Column(name = "quantity_res", nullable = false)
    public int getQuantityRes() {
        return this.quantityRes;
    }

    public void setQuantityRes(int quantityRes) {
        this.quantityRes = quantityRes;
    }

    @Column(name = "price", nullable = false, precision = 12, scale = 0)
    public float getPrice() {
        return this.price;
    }

    public void setPrice(float price) {
        this.price = price;
    }

    @Column(name = "staff_code_create", nullable = false, length = 20)
    public String getStaffCodeCreate() {
        return this.staffCodeCreate;
    }

    public void setStaffCodeCreate(String staffCodeCreate) {
        this.staffCodeCreate = staffCodeCreate;
    }

    @Column(name = "staff_code_update", nullable = false, length = 20)
    public String getStaffCodeUpdate() {
        return this.staffCodeUpdate;
    }

    public void setStaffCodeUpdate(String staffCodeUpdate) {
        this.staffCodeUpdate = staffCodeUpdate;
    }

    @Column(name = "status")
    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_time", length = 19)
    public Date getUpdatedTime() {
        return this.updatedTime;
    }

    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_time", length = 19)
    public Date getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

}
