package com.itss.vn.shops.entity;
// Generated Aug 2, 2017 4:33:40 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * OptionSet generated by hbm2java
 */
@Entity
@Table(name = "option_set", catalog = "shops", uniqueConstraints = @UniqueConstraint(columnNames = "option_set_code"))
public class OptionSet implements java.io.Serializable {

	private Integer optionSetId;
	private String optionSetCode;
	private String optionSetDesc;
	private String staffCode;
	private Integer status;
	private Date createdTime;
	private Date updatedTime;

	public OptionSet() {
	}

	public OptionSet(String optionSetCode, String optionSetDesc, String staffCode) {
		this.optionSetCode = optionSetCode;
		this.optionSetDesc = optionSetDesc;
		this.staffCode = staffCode;
	}

	public OptionSet(String optionSetCode, String optionSetDesc, String staffCode, Integer status, Date createdTime,
			Date updatedTime) {
		this.optionSetCode = optionSetCode;
		this.optionSetDesc = optionSetDesc;
		this.staffCode = staffCode;
		this.status = status;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "option_set_id", unique = true, nullable = false)
	public Integer getOptionSetId() {
		return this.optionSetId;
	}

	public void setOptionSetId(Integer optionSetId) {
		this.optionSetId = optionSetId;
	}

	@Column(name = "option_set_code", unique = true, nullable = false, length = 20)
	public String getOptionSetCode() {
		return this.optionSetCode;
	}

	public void setOptionSetCode(String optionSetCode) {
		this.optionSetCode = optionSetCode;
	}

	@Column(name = "option_set_desc", nullable = false)
	public String getOptionSetDesc() {
		return this.optionSetDesc;
	}

	public void setOptionSetDesc(String optionSetDesc) {
		this.optionSetDesc = optionSetDesc;
	}

	@Column(name = "staff_code", nullable = false, length = 20)
	public String getStaffCode() {
		return this.staffCode;
	}

	public void setStaffCode(String staffCode) {
		this.staffCode = staffCode;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_time", length = 19)
	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

}
