package com.itss.vn.shops.entity;
// Generated Aug 31, 2017 9:41:01 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * ProductDetail generated by hbm2java
 */
@Entity
@Table(name = "product_detail", catalog = "shops")
public class ProductDetail implements java.io.Serializable {

    private Integer id;
    private String productDetailDesc;
    private int attributeId;
    private int productId;
    private int finishedId;
    private String staffCodeCreate;
    private String staffCodeUpdate;
    private Integer status;
    private Date updatedTime;
    private Date createdTime;

    public ProductDetail() {
    }

    public ProductDetail(int id, String productDetailDesc, int attributeId, int productId, int finishedId,
                         String staffCodeCreate, String staffCodeUpdate) {
        this.id = id;
        this.productDetailDesc = productDetailDesc;
        this.attributeId = attributeId;
        this.productId = productId;
        this.finishedId = finishedId;
        this.staffCodeCreate = staffCodeCreate;
        this.staffCodeUpdate = staffCodeUpdate;
    }

    public ProductDetail(int id, String productDetailDesc, int attributeId, int productId, int finishedId,
                         String staffCodeCreate, String staffCodeUpdate, Integer status, Date updatedTime, Date createdTime) {
        this.id = id;
        this.productDetailDesc = productDetailDesc;
        this.attributeId = attributeId;
        this.productId = productId;
        this.finishedId = finishedId;
        this.staffCodeCreate = staffCodeCreate;
        this.staffCodeUpdate = staffCodeUpdate;
        this.status = status;
        this.updatedTime = updatedTime;
        this.createdTime = createdTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "product_detail_desc", nullable = false)
    public String getProductDetailDesc() {
        return this.productDetailDesc;
    }

    public void setProductDetailDesc(String productDetailDesc) {
        this.productDetailDesc = productDetailDesc;
    }

    @Column(name = "attribute_id", nullable = false)
    public int getAttributeId() {
        return this.attributeId;
    }

    public void setAttributeId(int attributeId) {
        this.attributeId = attributeId;
    }

    @Column(name = "product_id", nullable = false)
    public int getProductId() {
        return this.productId;
    }

    public void setProductId(int productId) {
        this.productId = productId;
    }

    @Column(name = "finished_id", nullable = false)
    public int getFinishedId() {
        return this.finishedId;
    }

    public void setFinishedId(int finishedId) {
        this.finishedId = finishedId;
    }

    @Column(name = "staff_code_create", nullable = false, length = 20)
    public String getStaffCodeCreate() {
        return this.staffCodeCreate;
    }

    public void setStaffCodeCreate(String staffCodeCreate) {
        this.staffCodeCreate = staffCodeCreate;
    }

    @Column(name = "staff_code_update", nullable = false, length = 20)
    public String getStaffCodeUpdate() {
        return this.staffCodeUpdate;
    }

    public void setStaffCodeUpdate(String staffCodeUpdate) {
        this.staffCodeUpdate = staffCodeUpdate;
    }

    @Column(name = "status")
    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_time", length = 19)
    public Date getUpdatedTime() {
        return this.updatedTime;
    }

    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_time", length = 19)
    public Date getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

}
