package com.itss.vn.shops.entity;
// Generated Aug 31, 2017 9:41:01 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * ProductGroups generated by hbm2java
 */
@Entity
@Table(name = "product_groups", catalog = "shops", uniqueConstraints = @UniqueConstraint(columnNames = "group_code"))
public class ProductGroups implements java.io.Serializable {

    private Integer groupId;
    private String groupCode;
    private String groupName;
    private String groupDesc;
    private Integer groupParentId;
    private String staffCodeCreate;
    private String staffCodeUpdate;
    private Integer status;
    private Date updatedTime;
    private Date createdTime;

    public ProductGroups() {
    }

    public ProductGroups(int groupId, String groupCode, String groupName, String staffCodeCreate,
                         String staffCodeUpdate) {
        this.groupId = groupId;
        this.groupCode = groupCode;
        this.groupName = groupName;
        this.staffCodeCreate = staffCodeCreate;
        this.staffCodeUpdate = staffCodeUpdate;
    }

    public ProductGroups(int groupId, String groupCode, String groupName, String groupDesc, Integer groupParentId,
                         String staffCodeCreate, String staffCodeUpdate, Integer status, Date updatedTime, Date createdTime) {
        this.groupId = groupId;
        this.groupCode = groupCode;
        this.groupName = groupName;
        this.groupDesc = groupDesc;
        this.groupParentId = groupParentId;
        this.staffCodeCreate = staffCodeCreate;
        this.staffCodeUpdate = staffCodeUpdate;
        this.status = status;
        this.updatedTime = updatedTime;
        this.createdTime = createdTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "group_id", unique = true, nullable = false)
    public Integer getGroupId() {
        return this.groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    @Column(name = "group_code", unique = true, nullable = false, length = 20)
    public String getGroupCode() {
        return this.groupCode;
    }

    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }

    @Column(name = "group_name", nullable = false, length = 50)
    public String getGroupName() {
        return this.groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    @Column(name = "group_desc")
    public String getGroupDesc() {
        return this.groupDesc;
    }

    public void setGroupDesc(String groupDesc) {
        this.groupDesc = groupDesc;
    }

    @Column(name = "group_parent_id")
    public Integer getGroupParentId() {
        return this.groupParentId;
    }

    public void setGroupParentId(Integer groupParentId) {
        this.groupParentId = groupParentId;
    }

    @Column(name = "staff_code_create", nullable = false, length = 20)
    public String getStaffCodeCreate() {
        return this.staffCodeCreate;
    }

    public void setStaffCodeCreate(String staffCodeCreate) {
        this.staffCodeCreate = staffCodeCreate;
    }

    @Column(name = "staff_code_update", nullable = false, length = 20)
    public String getStaffCodeUpdate() {
        return this.staffCodeUpdate;
    }

    public void setStaffCodeUpdate(String staffCodeUpdate) {
        this.staffCodeUpdate = staffCodeUpdate;
    }

    @Column(name = "status")
    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_time", length = 19)
    public Date getUpdatedTime() {
        return this.updatedTime;
    }

    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_time", length = 19)
    public Date getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

}
