package com.itss.vn.shops.entity;
// Generated Aug 2, 2017 4:33:40 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Staff generated by hbm2java
 */
@Entity
@Table(name = "staff", catalog = "shops", uniqueConstraints = @UniqueConstraint(columnNames = "staff_code"))
public class Staff implements java.io.Serializable {

	private Integer staffId;
	private String staffCode;
	private String staffName;
	private Date dateOfBirth;
	private String idNo;
	private String tel;
	private Integer status;
	private Date createdTime;
	private Date updatedTime;

	public Staff() {
	}

	public Staff(String staffCode, String staffName, Date dateOfBirth, String idNo, String tel) {
		this.staffCode = staffCode;
		this.staffName = staffName;
		this.dateOfBirth = dateOfBirth;
		this.idNo = idNo;
		this.tel = tel;
	}

	public Staff(String staffCode, String staffName, Date dateOfBirth, String idNo, String tel, Integer status,
			Date createdTime, Date updatedTime) {
		this.staffCode = staffCode;
		this.staffName = staffName;
		this.dateOfBirth = dateOfBirth;
		this.idNo = idNo;
		this.tel = tel;
		this.status = status;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "staff_id", unique = true, nullable = false)
	public Integer getStaffId() {
		return this.staffId;
	}

	public void setStaffId(Integer staffId) {
		this.staffId = staffId;
	}

	@Column(name = "staff_code", unique = true, nullable = false, length = 20)
	public String getStaffCode() {
		return this.staffCode;
	}

	public void setStaffCode(String staffCode) {
		this.staffCode = staffCode;
	}

	@Column(name = "staff_name", nullable = false, length = 50)
	public String getStaffName() {
		return this.staffName;
	}

	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_of_birth", nullable = false, length = 19)
	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Column(name = "id_no", nullable = false, length = 20)
	public String getIdNo() {
		return this.idNo;
	}

	public void setIdNo(String idNo) {
		this.idNo = idNo;
	}

	@Column(name = "tel", nullable = false, length = 12)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_time", length = 19)
	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

}
